#ifndef HOMESCREEN_ENUM_H
#define HOMESCREEN_ENUM_H

#include <QObject>
#include "HomeScreenDef.h"
class HomeScreen_Enum : public QObject
{
    Q_OBJECT

public:
    explicit HomeScreen_Enum(QObject *parent = nullptr)
    {
        Q_UNUSED(parent);
    }

    enum class QML_EVENT {
        EVENT_NOTHING,
        EVENT_SCREEN_TRANS,
        EVENT_ONSCREEN,
        EVENT_HIDEONSCREEN
    };

    enum class ENUM_HOME_MODEL {
        HOME_MENU_CHIEF_DOCTOR = 0,
        HOME_MENU_MY_DOCTOR,
        HOME_MENU_MY_NURSE,
        HOME_MENU_CURRENT_INFO,
        HOME_MENU_EXPERIMENT,
        HOME_MENU_24_HOURS,
        HOME_MENU_DRUG_INJECTION,
        HOME_MENU_MOLE_CULE,
        HOME_MENU_SLEEP,
        HOME_MENU_WHEEL_CHAIR
    };

    // define ENUM_EVENTS
    enum class ENUM_HOME_EVENT {
        EVENT_GO_TO_BACK = 0,
        EVENT_GO_TO_HOME_SCREEN,
        EVENT_GO_TO_HOME_WEATHER,
        EVENT_GO_TO_HOME_ADVANCED,
        EVENT_GO_TO_USER_PROFILE,
        EVENT_GO_TO_USER_DATA,
        EVENT_GO_TO_USER_DATA_REAL_TIME,
        EVENT_GO_TO_TECHNICAL_OVERVIEW,
        EVENT_GO_TO_SETTING,

        EVENT_SHOW_POPUP,
        EVENT_SHOW_POPUP_USER_PROFILE,
        EVENT_SHOW_POPUP_NO_CONNECTION,
        EVENT_HIDE_POPUP,

        EVENT_MAX = 65536
    };

//    enum class ENUM_POPUP_EVENT {

//    };
    enum class ENUM_WEATHER_PROPERTY {
        WEATHER_DAY_SHINE_BIG,
        WEATHER_DAY_SHINE_WINDY,
        WEATHER_DAY_SHINE_CLOUDY,
        WEATHER_DAY_SHINE_RAINNY,
        WEATHER_DAY_CLOUDY,
        WEATHER_DAY_CLOUDY_WIND,
        WEATHER_DAY_RAINNY,
        WEATHER_DAY_STORM,
        WEATHER_DAY_STORM_RAINNY,
        WEATHER_DAY_SNOW,
        WEATHER_NIGHT_CLOUDY,
        WEATHER_NIGHT_RAINNY
    };

    enum class ENUM_STATUSBAR_NETWORK_STRENGTH {
        STATUSBAR_NETWORK_NO_NETWORK = 0,
        STATUSBAR_NETWORK_VERY_WEAK,
        STATUSBAR_NETWORK_WEAK,
        STATUSBAR_NETWORK_NORMAL,
        STATUSBAR_NETWORK_GOOD,
        STATUSBAR_NETWORK_EXCELLENT
    };

    enum class ENUM_SETTING {
        SETTING_GENERAL,
        SETTING_NETWORK,
        SETTING_DEVICE,
        SETTING_USERPROFILE,
        SETTING_ABOUT
    };

    Q_ENUM(ENUM_HOME_MODEL)
    Q_ENUM(ENUM_HOME_EVENT)
    Q_ENUM(ENUM_WEATHER_PROPERTY)
    Q_ENUM(ENUM_STATUSBAR_NETWORK_STRENGTH)
    Q_ENUM(ENUM_SETTING)

signals:

public slots:

};



#endif // HOMESCREEN_ENUM_H
